from __future__ import annotations

import html
from pathlib import Path
from typing import Any


def render_voxelwise_lme_report(result: dict[str, Any], output_path: str | Path) -> Path:
    """Render an HTML report from parsed AFNI 3dLMEr results."""

    output = Path(output_path)
    output.parent.mkdir(parents=True, exist_ok=True)
    output_files = result.get("outputs", [])
    files_html = "".join(
        f"<li><a href='{html.escape(Path(item['path']).name)}'>{html.escape(item['kind'])}</a> "
        f"({html.escape(Path(item['path']).name)})</li>"
        for item in output_files
    ) or "<li>No AFNI output files were detected.</li>"
    stderr = result.get("stderr", "")
    warnings = stderr or "No AFNI stderr was returned."
    command = html.escape(result.get("command", ""))
    data_table = html.escape(Path(result["data_table"]).name)
    mask = html.escape(Path(result["mask"]).name) if result.get("mask") else "None"
    viewer = (
        f"<iframe class='viewer' src='{html.escape(Path(result['viewer']).name)}' "
        "title='Interactive voxelwise LME result'></iframe>"
        if result.get("viewer")
        else "<p>Interactive viewer was not generated by AFNI or is unavailable for this result format.</p>"
    )
    content = f"""<!doctype html>
<html><head><meta charset="utf-8"><title>Voxelwise LME: {html.escape(result['contrast'])}</title>
<style>
body {{ font-family: sans-serif; margin: 2rem; max-width: 1100px; }}
pre {{ white-space: pre-wrap; background: #f4f4f4; padding: 1rem; }}
.viewer {{ width: 100%; height: 600px; border: 1px solid #ccc; }}
</style></head><body>
<h1>Voxelwise longitudinal LME: {html.escape(result['contrast'])}</h1>
<h2>Analysis summary</h2>
<ul>
<li>Subjects included: {result['n_subjects']}</li>
<li>Groups: {html.escape(', '.join(result['groups']))}</li>
<li>Sessions: {html.escape(', '.join(result['sessions']))}</li>
<li>Model: <code>Group*Time</code> with random intercept <code>~1|Subj</code></li>
<li>Engine: AFNI 3dLMEr {html.escape(result.get('afni_version', 'unknown'))}</li>
<li>Mask: {mask}</li>
</ul>
<h2>Interaction result</h2>
<p>Primary group x time interaction. AFNI result files are preserved below.</p>
{viewer}
<h2>Main effects</h2>
<p>Group and time GLT outputs are included in the preserved AFNI result files.</p>
<ul>{files_html}</ul>
<h2>AFNI execution details</h2>
<p>Data table: <code>{data_table}</code></p>
<p>Runtime: {result.get('runtime_seconds', 0.0):.2f} seconds</p>
<h3>Generated command</h3><pre>{command}</pre>
<h3>AFNI warnings and stderr</h3><pre>{html.escape(warnings)}</pre>
</body></html>"""
    output.write_text(content, encoding="utf-8")
    return output
